// Commented out fonts are included in the legacy editor but broken because
// no source font files are available.

const FONTS = {
  Arial: 'Arial',
  'Times New Roman': 'Times New Roman',
  Courier: 'Courier',
  'Aleo-bold': 'aleobold',
  'Aleo-light': 'aleolight',
  'Alex Brush': 'alex_brushregular',
  Alghifari: '_mj_alghifariregular',
  Antiquabold: 'inknut_antiquabold',
  Antiquaregular: 'inknut_antiquaregular',
  Atzurbold: 'atzurbold',
  Badhead: 'badhead',
  // "Blenny": "blenny",
  'Boston Traffic': 'boston_trafficregular',
  Brushbear: 'swistblnk_duwhoers_brushRg',
  Bukhariscript: 'bukhari_script',
  Capture: 'capture_it_2regular',
  'Capture It': 'capture_itregular',
  Chivobold: 'chivobold',
  Choplinelight: 'choplinextralight',
  Choplinmedium: 'choplinmedium',
  Courgette: 'courgette',
  Debbyscript: 'debbyscript',
  Geomanist: 'geomanist',
  'Grand Hotel': 'grand_hotelregular',
  Handmade: 'nexa_rust_handmadeextended',
  Homiziolight: 'homiziolight',
  Kaushanscript: 'KaushanScript-Regular',
  // "Kinescope": "kinescope",
  'King Basil': 'king_basil_literegular',
  Liberalhand: 'liberal_handbold',
  Luthierbold: 'luthierbold',
  Luthierregular: 'luthierregular',
  Malua: 'swistblnk_moalang_melintangRg',
  Melo: 'meloregular',
  Moabear: 'swistblnk_moabhoers_bold',
  Modum: 'modumregular',
  Nickainley: 'nickainley',
  Niconne: 'niconne',
  Norwester: 'norwester',
  // "Proxima": "proxima-nova",
  Reefbold: 'Reefbold',
  Rhodium: 'rhodium',
  Rubikbitalic: 'rubikbold_italic',
  Rubikitalic: 'rubikblack_italic',
  Rubikregular: 'rubikregular',
  Rustscript: 'nexa_rust_script_l0regular',
  Sansitabold: 'sansitablack',
  Sansitareg: 'sansitabold',
  Santelia: 'santelia',
  Santeliarough: 'santelia_roughline_two',
  Slablack: 'nexa_rust_slabblack_shadow_01',
  Sortdecai: 'sortdecai',
  Sortdecaibrush: 'sortdecaibrush',
  Streetwear: 'streetwear',
  Swistblnk: 'swistblnk',
  Variane: 'variane',
  Worksansbold: 'work_sansbold',
  Worksanshairline: 'work_sanshairline',
  Worksansregular: 'work_sansregular',
  Worksansthin: 'work_sansthin',
  Xplorer: 'xplor_boldregular',
};

export default FONTS;
